language: python
branches:
  only:
  - src
install:
- pip install -r requirements.txt
script:
- make github
env:
  global:
  - secure: TVaac0mG9VBJtQD2KEc40QM/qUJ10J1l99I1+LUQWd5KHJ3UA/SotKiJu2Yk58iSipB79xZjnrrwrKar5DYB/nFgA7tDyVxZcJyFRmjKqq9DAmZhqzZnR/FIIaYA+CZ849geG9cCempVE7yIkWl1kx4I3Yz1erSWanjqT3J5sTE=
